import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useEffect } from 'react'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>FlashSwap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>test</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://uniswap.org/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/assets/uniswap-logo.svg" alt="" width={100} height={60} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
